version: '3.8'

services:
  next-front:
    container_name: next-front
    build:
      context: ./next-front
      dockerfile: Dockerfile
    ports:
      - 3000:${FRONT_PORT}
    command: npm run dev
    volumes:
      - ./next-front:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - api

  react-front:
    container_name: react-front
    build:
      context: ./react-front
      dockerfile: Dockerfile
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    environment:
      - FRONT_PORT=${FRONT_PORT}
    command: npm start
    volumes:
      - ./react-front:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - $API_PORT:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080